Added formula for NEST-2.2.2
Slightly outdated, but used to successfully build using gcc in Xcode 5.x
on OSX 10.7, and at least on early 10.8 versions

Fails using clang due to constructor visibility in STL's iterator:
> randomgen.cpp:31:3: error: field of type
> 'std::vector<double>::const_iterator' (aka '__wrap_iter<const_pointer>')
> has private constructor